### ISSUE TITLE
Install Wizard (codname Zen) First Release

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zen#16]
- finish zen for the single admin (printing out JCL that can be edited for multi-admins for security tasks, through zwe doing this)
- basic certificate setup (the 5 scenarios outlined in https://github.com/zowe/zowe-install-packaging/blob/16936ceaf17153d305aa130335d4c49899d5a7ab/example-zowe.yaml#L97-L255
- make prompting for all of yaml, in 2 ways: "html form"-like boxes, that are derived from the schema, and "just the yaml" editor where people can see the real yaml and customize it, or paste in previously used stuff
- distribute for windows & mac & linux (ubuntu zlinux available to us)
- must allow offline upload of pax (dont download directly from jfrog without asking)
- if we do direct download from jfrog, we need license agreement page
- what is our documentation story?
   * how to install
   * what it does and doesnt yet do
   * what users does it satisfy (and who should bother - its not for installing CLI for example)

- who owns this long-term? is it a new squad? or systems squad?
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zen/issues/23
- [ ] https://github.com/zowe/zen/issues/75
- [ ] https://github.com/zowe/zen/issues/74
- [ ] https://github.com/zowe/zen/issues/73
- [ ] https://github.com/zowe/zen/issues/72
- [ ] https://github.com/zowe/zen/issues/71
- [ ] https://github.com/zowe/zen/issues/70
- [ ] https://github.com/zowe/zen/issues/69
- [ ] https://github.com/zowe/zen/issues/19
- [ ] https://github.com/zowe/zen/issues/27
- [ ] https://github.com/zowe/zen/issues/24
- [ ] https://github.com/zowe/zen/issues/22
- [ ] https://github.com/zowe/zen/issues/21
- [ ] https://github.com/zowe/zen/issues/20
- [ ] https://github.com/zowe/zen/issues/26
- [ ] https://github.com/zowe/zen/issues/25
- [ ] https://github.com/zowe/zen/issues/186
- [ ] https://github.com/zowe/zen/issues/182
- [ ] https://github.com/zowe/zen/issues/185
- [ ] https://github.com/zowe/zen/issues/187
- [ ] https://github.com/zowe/zen/issues/184
- [ ] https://github.com/zowe/zen/issues/188
- [ ] https://github.com/zowe/zen/issues/189
- [ ] https://github.com/zowe/zen/issues/190
```

**Comment by PWFlyMan** [comment]
This looks good. Given adequate resources and vendors interested a squad would seem sensible but that might be a challenge.

**Comment by DivergentEuropeans** [comment]
@PWFlyMan Is this ready to close?
